language: php
os:
  - linux

php:
    - 7.4
    - 7.3
    - 7.2
    - 7.1
    - 5.6

services:
  - mysql

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - mysql -e 'CREATE DATABASE s2_rose_test;'

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction

before_script:
  - cp tests/config.php.dist tests/config.php

script:
  - php bin/codecept run

cache:
    directories:
        - vendor
        - $HOME/.composer/cache
