name: Test on SQLite

on: [ push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        operating_system:
          - 'ubuntu-22.04'
        php_versions:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'

    runs-on: '${{ matrix.operating_system }}'

    steps:
      - uses: actions/checkout@v3

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_versions }}

      - name: Install dependencies
        run: COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-interaction

      - name: Prepare config
        run: cp tests/config.php.dist.sqlite tests/config.php

      - name: Run test cases
        run: php bin/codecept run --skip-group profile

      - name: Run profiling
        if: success() || failure()
        run: php bin/codecept run -g profile -d