name: Tests

on: [ push ]

env:
  DB_DATABASE: s2_rose_test
  DB_USER: root
  DB_PASSWORD: root

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        operating_system: ['ubuntu-20.04', 'ubuntu-18.04']
        php_versions:
          - '7.4'
          - '8.0'
          - '8.1'
        include:
          -
            operating_system: 'ubuntu-22.04'
            php_versions: 8.1
          -
            operating_system: 'ubuntu-22.04'
            php_versions: 8.2

    runs-on: '${{ matrix.operating_system }}'

    steps:
      - uses: actions/checkout@v2

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_versions }}

      - name: Install dependencies
        run: COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-interaction

      - name: Prepare config
        run: cp tests/config.php.dist tests/config.php

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          mysql -e 'SELECT version();' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Run test cases
        run: php bin/codecept run --skip-group profile

      - name: Run profiling
        run: php bin/codecept run -g profile -d